[versions]
jupiter = "5.9.3"

[libraries]
dronefleet-mavlink = "io.dronefleet.mavlink:mavlink:1.1.9"

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
